name: Pull and Run Docker Image Locally

on:
  workflow_dispatch:  # Manually trigger this workflow

jobs:
  run_docker_locally:
    runs-on: self-hosted  # Specify that this job runs on your self-hosted runner

    steps:
      - name: Pull Docker image
        run: |
          docker pull skgoswami/react-hello:latest

      - name: Stop and Remove Existing Container
        run: |
          docker stop react-hello || true
          docker rm react-hello || true

      - name: Run Docker Container
        run: |
          docker run -d --name react-hello -p 3000:3000 skgoswami/react-hello:latest
