name: Pull and Run Docker Image Locally

on:
  workflow_dispatch:  # Manually trigger this workflow

jobs:
  run_docker_locally:
    runs-on: self-hosted  # Specify that this job runs on your self-hosted runner

    steps:
      - name: Pull Docker image
        run: |
          docker pull skgoswami/hello-react:latest

      - name: Stop and Remove Existing Container
        run: |
          docker stop hello-react || true
          docker rm hello-react || true

      - name: Run Docker Container
        run: |
          docker run -d --name hello-react -p 3000:3000 skgoswami/hello-react:latest
