name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Run this workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build --platform linux/arm64/v8 -t skgoswami/react-hello:latest .
          docker push skgoswami/react-hello:latest

      - name: Trigger local workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'skgoswami2005',
              repo: 'react-hello',
              workflow_id: 'docker-run.yml',
              ref: 'main'
            })
